//
// Comment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Comment: Codable {

    /** comment content */
    public var body: String
    /** username of person posting comment */
    public var authorName: String
    public var authorProfilePicUUID: String?
    /** times and date of comment */
    public var timestamp: String? //
    public var votes: [Vote]?
    /** True or false value stating if comment is flagged or reported */
    public var isFlagged: Bool?
    /** True or false value stating whether a user deleted the comment */
    public var isDeleted: Bool?
    /** True or false value stating whether the comment has been updated since being posted */
    public var isEdited: Bool?

    public init(body: String, authorName: String, authorProfilePicUUID: String?, timestamp: String?, votes: [Vote]?, isFlagged: Bool?, isDeleted: Bool?, isEdited: Bool?) {
        self.body = body
        self.authorName = authorName
        self.authorProfilePicUUID = authorProfilePicUUID
        self.timestamp = timestamp
        self.votes = votes
        self.isFlagged = isFlagged
        self.isDeleted = isDeleted
        self.isEdited = isEdited
    }


}

