//
// Profile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Profile: Codable {

    /** Profile picture ID */
    public var profilePicUUID: String?
    /** Total profile points used to determine level */
    public var totalPoints: Double
    public var level: Level?
    public var interests: [Interest]?
    /** -(Profile rating Only for businesses/professionals) */
    public var rating: Int?

}

