//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct User: Codable {
    
    /** Unique user identifier */
    public var username: String
    /** Password (8-16 characters) */
    public var password: String
    /** Website URL */
    public var website: String?
    /** Cell phone or contact number */
    public var phoneNumber: String?
    /** Email address used for notifications and authentication */
    public var email: String?
    public var address: Address?
    public var profile: Profile?
    /** True or false value stating whether account is for business */
    public var isBusiness: Bool

    public init(username: String, password: String, website: String?, phoneNumber: String?, email: String?, address: Address?, profile: Profile?, isBusiness: Bool) {
        self.username = username
        self.password = password
        self.website = website
        self.phoneNumber = phoneNumber
        self.email = email
        self.address = address
        self.profile = profile
        self.isBusiness = isBusiness
    }


}

