//
// Vote.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Vote: Codable {

    /** UserId of the person that voted */
    public var voterID: String?
    /** True or false value dictating whether the vote was positive or not */
    public var isUpVote: Bool?

    public init(voterID: String?, isUpVote: Bool?) {
        self.voterID = voterID
        self.isUpVote = isUpVote
    }
}

