//
//  CountryViewModel.swift
//  Aweh
//
//  Created by Divine.Dube on 2020/10/31.
//  Copyright © 2020 com.github.aweh. All rights reserved.
//

import Foundation

struct CountryViewModel {
    
    var name: String {
        let current = Locale(identifier: "en_US")
        return current.localizedString(forRegionCode: countryCode) ?? countryCode
    }
    
    let countryCode: String
    let phoneExtension: String

}

extension CountryViewModel {
    static var countries: [CountryViewModel] {
        return [
            CountryViewModel(countryCode: "AF", phoneExtension: "93"),
            CountryViewModel(countryCode: "AL", phoneExtension: "355"),
            CountryViewModel(countryCode: "DZ", phoneExtension: "213"),
            CountryViewModel(countryCode: "AS", phoneExtension: "1"),
            CountryViewModel(countryCode: "AD", phoneExtension: "376"),
            CountryViewModel(countryCode: "AO", phoneExtension: "244"),
            CountryViewModel(countryCode: "AI", phoneExtension: "1"),
            CountryViewModel(countryCode: "AQ", phoneExtension: "672"),
            CountryViewModel(countryCode: "AG", phoneExtension: "1"),
            CountryViewModel(countryCode: "AR", phoneExtension: "54"),
            CountryViewModel(countryCode: "AM", phoneExtension: "374"),
            CountryViewModel(countryCode: "AW", phoneExtension: "297"),
            CountryViewModel(countryCode: "AU", phoneExtension: "61"),
            CountryViewModel(countryCode: "AT", phoneExtension: "43"),
            CountryViewModel(countryCode: "AZ", phoneExtension: "994"),
            
            CountryViewModel(countryCode: "BS", phoneExtension: "1"),
            CountryViewModel(countryCode: "BH", phoneExtension: "973"),
            CountryViewModel(countryCode: "BD", phoneExtension: "880"),
            CountryViewModel(countryCode: "BB", phoneExtension: "1"),
            CountryViewModel(countryCode: "BY", phoneExtension: "375"),
            CountryViewModel(countryCode: "BE", phoneExtension: "32"),
            CountryViewModel(countryCode: "BZ", phoneExtension: "501"),
            CountryViewModel(countryCode: "BJ", phoneExtension: "229"),
            CountryViewModel(countryCode: "BM", phoneExtension: "1"),
            CountryViewModel(countryCode: "BT", phoneExtension: "975"),
            CountryViewModel(countryCode: "BO", phoneExtension: "591"),
            CountryViewModel(countryCode: "BA", phoneExtension: "387"),
            CountryViewModel(countryCode: "BW", phoneExtension: "267"),
            CountryViewModel(countryCode: "BR", phoneExtension: "55"),
            CountryViewModel(countryCode: "IO", phoneExtension: "246"),
            CountryViewModel(countryCode: "VG", phoneExtension: "1"),
            CountryViewModel(countryCode: "BN", phoneExtension: "673"),
            CountryViewModel(countryCode: "BG", phoneExtension: "359"),
            CountryViewModel(countryCode: "BF", phoneExtension: "226"),
            CountryViewModel(countryCode: "BI", phoneExtension: "257"),
            CountryViewModel(countryCode: "KH", phoneExtension: "855"),
            CountryViewModel(countryCode: "CM", phoneExtension: "237"),
            CountryViewModel(countryCode: "CA", phoneExtension: "1"),
            CountryViewModel(countryCode: "CV", phoneExtension: "238"),
            
            CountryViewModel(countryCode: "KY", phoneExtension: "1"),
            CountryViewModel(countryCode: "CF", phoneExtension: "236"),
            CountryViewModel(countryCode: "TD", phoneExtension: "235"),
            CountryViewModel(countryCode: "CL", phoneExtension: "56"),
            CountryViewModel(countryCode: "CN", phoneExtension: "86"),
            CountryViewModel(countryCode: "CX", phoneExtension: "61"),
            CountryViewModel(countryCode: "CC", phoneExtension: "61"),
            CountryViewModel(countryCode: "CO", phoneExtension: "57"),
            CountryViewModel(countryCode: "KM", phoneExtension: "269"),
            CountryViewModel(countryCode: "CK", phoneExtension: "682"),
            CountryViewModel(countryCode: "CR", phoneExtension: "506"),
            CountryViewModel(countryCode: "HR", phoneExtension: "385"),
            CountryViewModel(countryCode: "CU", phoneExtension: "53"),
            CountryViewModel(countryCode: "CW", phoneExtension: "599"),
            CountryViewModel(countryCode: "CY", phoneExtension: "357"),
            CountryViewModel(countryCode: "CZ", phoneExtension: "420"),
            CountryViewModel(countryCode: "CD", phoneExtension: "243"),
            
            CountryViewModel(countryCode: "DK", phoneExtension: "45"),
            CountryViewModel(countryCode: "DJ", phoneExtension: "253"),
            CountryViewModel(countryCode: "DM", phoneExtension: "1"),
            CountryViewModel(countryCode: "DO", phoneExtension: "1"),
            
            CountryViewModel(countryCode: "TL", phoneExtension: "670"),
            CountryViewModel(countryCode: "EC", phoneExtension: "593"),
            CountryViewModel(countryCode: "EG", phoneExtension: "20"),
            CountryViewModel(countryCode: "SV", phoneExtension: "503"),
            CountryViewModel(countryCode: "GQ", phoneExtension: "240"),
            CountryViewModel(countryCode: "ER", phoneExtension: "291"),
            CountryViewModel(countryCode: "EE", phoneExtension: "372"),
            CountryViewModel(countryCode: "ET", phoneExtension: "251"),
            
            CountryViewModel(countryCode: "FK", phoneExtension: "500"),
            CountryViewModel(countryCode: "FO", phoneExtension: "298"),
            CountryViewModel(countryCode: "FJ", phoneExtension: "679"),
            CountryViewModel(countryCode: "FI", phoneExtension: "358"),
            CountryViewModel(countryCode: "FR", phoneExtension: "33"),
            CountryViewModel(countryCode: "PF", phoneExtension: "689"),
            
            CountryViewModel(countryCode: "GA", phoneExtension: "241"),
            CountryViewModel(countryCode: "GM", phoneExtension: "220"),
            CountryViewModel(countryCode: "GE", phoneExtension: "995"),
            CountryViewModel(countryCode: "DE", phoneExtension: "49"),
            CountryViewModel(countryCode: "GH", phoneExtension: "233"),
            CountryViewModel(countryCode: "GI", phoneExtension: "350"),
            CountryViewModel(countryCode: "GR", phoneExtension: "30"),
            CountryViewModel(countryCode: "GL", phoneExtension: "299"),
            CountryViewModel(countryCode: "GD", phoneExtension: "1"),
            CountryViewModel(countryCode: "GU", phoneExtension: "1"),
            CountryViewModel(countryCode: "GT", phoneExtension: "502"),
            CountryViewModel(countryCode: "GG", phoneExtension: "44"),
            CountryViewModel(countryCode: "GN", phoneExtension: "224"),
            CountryViewModel(countryCode: "GW", phoneExtension: "245"),
            CountryViewModel(countryCode: "GY", phoneExtension: "592"),
            
            CountryViewModel(countryCode: "HT", phoneExtension: "509"),
            CountryViewModel(countryCode: "HN", phoneExtension: "504"),
            CountryViewModel(countryCode: "HK", phoneExtension: "852"),
            CountryViewModel(countryCode: "HU", phoneExtension: "36"),
            
            CountryViewModel(countryCode: "IS", phoneExtension: "354"),
            CountryViewModel(countryCode: "IN", phoneExtension: "91"),
            CountryViewModel(countryCode: "ID", phoneExtension: "62"),
            CountryViewModel(countryCode: "IR", phoneExtension: "98"),
            CountryViewModel(countryCode: "IQ", phoneExtension: "964"),
            CountryViewModel(countryCode: "IE", phoneExtension: "353"),
            CountryViewModel(countryCode: "IM", phoneExtension: "44"),
            CountryViewModel(countryCode: "IL", phoneExtension: "972"),
            CountryViewModel(countryCode: "IT", phoneExtension: "39"),
            CountryViewModel(countryCode: "CI", phoneExtension: "225"),
            
            CountryViewModel(countryCode: "JM", phoneExtension: "1"),
            CountryViewModel(countryCode: "JP", phoneExtension: "81"),
            CountryViewModel(countryCode: "JE", phoneExtension: "44"),
            CountryViewModel(countryCode: "JO", phoneExtension: "962"),
            
            CountryViewModel(countryCode: "KZ", phoneExtension: "7"),
            CountryViewModel(countryCode: "KE", phoneExtension: "254"),
            CountryViewModel(countryCode: "KI", phoneExtension: "686"),
            CountryViewModel(countryCode: "XK", phoneExtension: "383"),
            CountryViewModel(countryCode: "KW", phoneExtension: "965"),
            CountryViewModel(countryCode: "KG", phoneExtension: "996"),
            
            CountryViewModel(countryCode: "LA", phoneExtension: "856"),
            CountryViewModel(countryCode: "LV", phoneExtension: "371"),
            CountryViewModel(countryCode: "LB", phoneExtension: "961"),
            CountryViewModel(countryCode: "LS", phoneExtension: "266"),
            CountryViewModel(countryCode: "LR", phoneExtension: "231"),
            CountryViewModel(countryCode: "LY", phoneExtension: "218"),
            CountryViewModel(countryCode: "LI", phoneExtension: "423"),
            CountryViewModel(countryCode: "LT", phoneExtension: "370"),
            CountryViewModel(countryCode: "LU", phoneExtension: "352"),
            
            CountryViewModel(countryCode: "MO", phoneExtension: "853"),
            CountryViewModel(countryCode: "MK", phoneExtension: "389"),
            CountryViewModel(countryCode: "MG", phoneExtension: "261"),
            CountryViewModel(countryCode: "MW", phoneExtension: "265"),
            CountryViewModel(countryCode: "MY", phoneExtension: "60"),
            CountryViewModel(countryCode: "MV", phoneExtension: "960"),
            CountryViewModel(countryCode: "ML", phoneExtension: "223"),
            CountryViewModel(countryCode: "MT", phoneExtension: "356"),
            CountryViewModel(countryCode: "MH", phoneExtension: "692"),
            CountryViewModel(countryCode: "MR", phoneExtension: "222"),
            CountryViewModel(countryCode: "MU", phoneExtension: "230"),
            CountryViewModel(countryCode: "YT", phoneExtension: "262"),
            CountryViewModel(countryCode: "MX", phoneExtension: "52"),
            CountryViewModel(countryCode: "FM", phoneExtension: "691"),
            CountryViewModel(countryCode: "MD", phoneExtension: "373"),
            CountryViewModel(countryCode: "MC", phoneExtension: "377"),
            CountryViewModel(countryCode: "MN", phoneExtension: "976"),
            CountryViewModel(countryCode: "ME", phoneExtension: "382"),
            CountryViewModel(countryCode: "MS", phoneExtension: "1"),
            CountryViewModel(countryCode: "MA", phoneExtension: "212"),
            CountryViewModel(countryCode: "MZ", phoneExtension: "258"),
            CountryViewModel(countryCode: "MM", phoneExtension: "95"),
            
            CountryViewModel(countryCode: "NA", phoneExtension: "264"),
            CountryViewModel(countryCode: "NR", phoneExtension: "674"),
            CountryViewModel(countryCode: "NP", phoneExtension: "977"),
            CountryViewModel(countryCode: "NL", phoneExtension: "31"),
            CountryViewModel(countryCode: "AN", phoneExtension: "599"),
            CountryViewModel(countryCode: "NC", phoneExtension: "687"),
            CountryViewModel(countryCode: "NZ", phoneExtension: "64"),
            CountryViewModel(countryCode: "NI", phoneExtension: "505"),
            CountryViewModel(countryCode: "NE", phoneExtension: "227"),
            CountryViewModel(countryCode: "NG", phoneExtension: "234"),
            CountryViewModel(countryCode: "NU", phoneExtension: "683"),
            CountryViewModel(countryCode: "KP", phoneExtension: "850"),
            CountryViewModel(countryCode: "MP", phoneExtension: "1"),
            CountryViewModel(countryCode: "NO", phoneExtension: "47"),
            
            CountryViewModel(countryCode: "OM", phoneExtension: "968"),
            
            CountryViewModel(countryCode: "PK", phoneExtension: "92"),
            CountryViewModel(countryCode: "PW", phoneExtension: "680"),
            CountryViewModel(countryCode: "PS", phoneExtension: "970"),
            CountryViewModel(countryCode: "PA", phoneExtension: "507"),
            CountryViewModel(countryCode: "PG", phoneExtension: "675"),
            CountryViewModel(countryCode: "PY", phoneExtension: "595"),
            CountryViewModel(countryCode: "PE", phoneExtension: "51"),
            CountryViewModel(countryCode: "PH", phoneExtension: "63"),
            CountryViewModel(countryCode: "PN", phoneExtension: "64"),
            CountryViewModel(countryCode: "PL", phoneExtension: "48"),
            CountryViewModel(countryCode: "PT", phoneExtension: "351"),
            CountryViewModel(countryCode: "PR", phoneExtension: "1"),
            
            CountryViewModel(countryCode: "QA", phoneExtension: "974"),
            
            CountryViewModel(countryCode: "CG", phoneExtension: "242"),
            CountryViewModel(countryCode: "RE", phoneExtension: "262"),
            CountryViewModel(countryCode: "RO", phoneExtension: "40"),
            CountryViewModel(countryCode: "RU", phoneExtension: "7"),
            CountryViewModel(countryCode: "RW", phoneExtension: "250"),
            
            CountryViewModel(countryCode: "BL", phoneExtension: "590"),
            CountryViewModel(countryCode: "SH", phoneExtension: "290"),
            CountryViewModel(countryCode: "KN", phoneExtension: "1"),
            CountryViewModel(countryCode: "LC", phoneExtension: "1"),
            CountryViewModel(countryCode: "MF", phoneExtension: "590"),
            CountryViewModel(countryCode: "PM", phoneExtension: "508"),
            
            CountryViewModel(countryCode: "VC", phoneExtension: "1"),
            CountryViewModel(countryCode: "WS", phoneExtension: "685"),
            CountryViewModel(countryCode: "SM", phoneExtension: "378"),
            CountryViewModel(countryCode: "ST", phoneExtension: "239"),
            CountryViewModel(countryCode: "SA", phoneExtension: "966"),
            CountryViewModel(countryCode: "SN", phoneExtension: "221"),
            CountryViewModel(countryCode: "RS", phoneExtension: "381"),
            CountryViewModel(countryCode: "SC", phoneExtension: "248"),
            CountryViewModel(countryCode: "SL", phoneExtension: "232"),
            CountryViewModel(countryCode: "SG", phoneExtension: "65"),
            CountryViewModel(countryCode: "SX", phoneExtension: "1"),
            CountryViewModel(countryCode: "SK", phoneExtension: "421"),
            CountryViewModel(countryCode: "SI", phoneExtension: "386"),
            CountryViewModel(countryCode: "SB", phoneExtension: "677"),
            CountryViewModel(countryCode: "SO", phoneExtension: "252"),
            CountryViewModel(countryCode: "ZA", phoneExtension: "27"),
            CountryViewModel(countryCode: "KR", phoneExtension: "82"),
            CountryViewModel(countryCode: "SS", phoneExtension: "211"),
            CountryViewModel(countryCode: "ES", phoneExtension: "34"),
            CountryViewModel(countryCode: "LK", phoneExtension: "94"),
            CountryViewModel(countryCode: "SD", phoneExtension: "249"),
            CountryViewModel(countryCode: "SR", phoneExtension: "597"),
            CountryViewModel(countryCode: "SJ", phoneExtension: "47"),
            CountryViewModel(countryCode: "SZ", phoneExtension: "268"),
            CountryViewModel(countryCode: "SE", phoneExtension: "46"),
            CountryViewModel(countryCode: "CH", phoneExtension: "41"),
            CountryViewModel(countryCode: "SY", phoneExtension: "963"),
            
            CountryViewModel(countryCode: "TW", phoneExtension: "886"),
            CountryViewModel(countryCode: "TJ", phoneExtension: "992"),
            CountryViewModel(countryCode: "TZ", phoneExtension: "255"),
            CountryViewModel(countryCode: "TH", phoneExtension: "66"),
            CountryViewModel(countryCode: "TG", phoneExtension: "228"),
            CountryViewModel(countryCode: "TK", phoneExtension: "690"),
            CountryViewModel(countryCode: "TO", phoneExtension: "676"),
            CountryViewModel(countryCode: "TT", phoneExtension: "1"),
            CountryViewModel(countryCode: "TN", phoneExtension: "216"),
            CountryViewModel(countryCode: "TR", phoneExtension: "90"),
            CountryViewModel(countryCode: "TM", phoneExtension: "993"),
            CountryViewModel(countryCode: "TC", phoneExtension: "1"),
            CountryViewModel(countryCode: "TV", phoneExtension: "688"),
            
            CountryViewModel(countryCode: "VI", phoneExtension: "1"),
            CountryViewModel(countryCode: "UG", phoneExtension: "256"),
            CountryViewModel(countryCode: "UA", phoneExtension: "380"),
            CountryViewModel(countryCode: "AE", phoneExtension: "971"),
            CountryViewModel(countryCode: "GB", phoneExtension: "44"),
            CountryViewModel(countryCode: "US", phoneExtension: "1"),
            CountryViewModel(countryCode: "UY", phoneExtension: "598"),
            CountryViewModel(countryCode: "UZ", phoneExtension: "998"),
            
            CountryViewModel(countryCode: "VU", phoneExtension: "678"),
            CountryViewModel(countryCode: "VA", phoneExtension: "379"),
            CountryViewModel(countryCode: "VE", phoneExtension: "58"),
            CountryViewModel(countryCode: "VN", phoneExtension: "84"),
            
            CountryViewModel(countryCode: "WF", phoneExtension: "681"),
            CountryViewModel(countryCode: "EH", phoneExtension: "212"),
            
            CountryViewModel(countryCode: "YE", phoneExtension: "967"),
            
            CountryViewModel(countryCode: "ZM", phoneExtension: "260"),
            CountryViewModel(countryCode: "ZW", phoneExtension: "263")
        ]
    }
}
