//
// Address.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Address: Codable {

    /** Street name and building number */
    public var street: String?
    /** City/Town */
    public var city: String?
    /** State or province depending on country */
    public var state: String?
    /** Postal code */
    public var postCode: String?
    /** Country of address */
    public var country: String?

    public init(street: String?, city: String?, state: String?, postCode: String?, country: String?) {
        self.street = street
        self.city = city
        self.state = state
        self.postCode = postCode
        self.country = country
    }


}

