//
// Interest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Interest: Codable {

    /** Title of interest (example: Food, Sports, Cars) */
    public var title: String
    /** Description of interest */
    public var _description: String

    public init(title: String, _description: String) {
        self.title = title
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case _description = "description"
    }

}

